- css/style-sass-components.css
- fonts/europa-icons/europa-icons-codes.css
- sass/components/_footer.scss
- sass/components/html/footer-improved.html
- sass/components/html/footer.html
> EUTHEME-154 (Custom footer)

- css/style-sass-base.css
- sass/base/_lists.scss
- sass/base/html/lists.html
> EUTHEME-164 (Improvements on the lists, adding nested lists to demo)

- css/style-sass-components.css
- sass/components/_listing.scss
- sass/components/html/listing__wrapper--three-columns-featured-item.html
There also a fix on a listing template about default images.
> EUTHEME-222 (Removing no-padding modifier from the listing)

- css/style-sass-base.css
- css/style-sass-components.css
- sass/base/_blockquote.scss
- sass/base/_headings.scss
- sass/base/_link.scss
- sass/base/_lists.scss
- sass/base/_paragraphs.scss
> EUTHEME-223 (Renaming Text component to Typography)

- css/style-sass-components.css
- sass/components/_date-block.scss
> EUTHEME-187 (Renaming live-streaming class to ongoing)

- template.php
- templates/comment/comment-wrapper.tpl.php
> EUTHEME-149 (comment form fixes)

- template.php
Together with:
https://github.com/ec-europa/ec-europa-theme-tools/pull/44
Next step will be to make all the templates "conditional" and by doing this also reducing the number of templates to maintain.
The logic used it's just a clone of what we already had in the preprocess_page.
> EUTHEME-169  (Providing simple logic to make templates conditionals)

- css/style-sass-components.css
- sass/components/_listing.scss
- sass/components/html/listing--navigation.html
> EUTHEME-103 (Rewrite css for the listing navigation modifier)

- europa.info
- template.php
- theme-settings.php
> EUTHEME-229 (Providing a configuration setting for the breadcrumb menu)

- css/style-sass-components.css
- js/europa.js
- sass/app_components.scss
- sass/base/_btn.scss
- sass/base/html/btn-block.html
- sass/base/html/btn-collapse.html
- sass/base/html/btn-group.html
- sass/base/html/btn.html
- sass/components/_page-header.scss
- sass/components/html/page-header--informational.html
- sass/components/html/page-header--political.html
- sass/components/html/page-header-complete.html
> EUTHEME-231 (page header with site identitification and no meta)

- template.php
**Notes:**
This pr is to be reviwed with https://github.com/ec-europa/ec-europa-theme-tools/pull/46
> EUTHEME-218 (Language switcher [ adding nexteuropa_language_selector_site_popup])

- css/style-sass-components.css
- sass/_variables.scss
- sass/components/_breadcrumb.scss
- sass/components/_date-block.scss
- sass/components/_datepicker.scss
- sass/components/_file-upload.scss
- sass/components/_footer.scss
- sass/components/_inpage-nav.scss
- sass/components/_lang-select-page.scss
- sass/components/_link-block.scss
- sass/components/_page-header.scss
- sass/components/_site-user-menu.scss
> EUTHEME-176 (Colors - Change naming and hexadecimal codes - Follow-up)

- css/style-sass-components.css
- europa.info
- sass/components/_lang-select-site.scss
- template.php
- templates/block/block--language-selector-site.tpl.php
- templates/system/page--ds.tpl.php
- templates/system/page.tpl.php
- theme-settings.php
> EUTHEME-249 (Site header)

- template.php
**Notes:**
This should be included in the 0.92 release as well.
> EUTHEME-250 (Adding local tasks to taxonomy pages)

- css/style-sass-components.css
- sass/components/_listing.scss
- sass/components/html/listing--teaser.html
- sass/components/html/listing__wrapper--row-three.html
> EUTHEME-266 (Fixing the component Listing CTA)

- css/style-sass-components.css
- sass/base/_btn.scss
> EUTHEME-261 (Create a modifier for buttons to have a right margin)

- css/style-sass-components.css
- sass/base/_link.scss
- sass/components/_listing.scss
> EUTHEME-276 (Listing component - External icon link)

- css/style-sass-components.css
- sass/components/_gallery.scss
- sass/components/html/gallery-overlay.html
**Notes:**
Minor fixes and improvements.
> EUTHEME-55 (Media gallery overlay component)

- css/style-sass-components.css
- sass/components/_listing.scss
- sass/components/html/listing--navigation.html
> EUTHEME-294 (Fixing listing navigation)

- css/style-sass-components.css
- europa.info
- sass/components/_breadcrumb.scss
- sass/components/_page-header.scss
- template.php
- templates/system/page.tpl.php
- theme-settings.php
> EUTHEME-297 (Implementing the "basic" header")

- template.php
**Notes:**
To be reviewed together with: https://github.com/ec-europa/ec-europa-theme-tools/pull/85
> EUTHEME-298 (Reorganizing columns in ds templates)

- europa.info
- templates/system/page.tpl.php
- theme-settings.php
> EUTHEME-299 (Providing the setting and the logic for the page.tpl.php)

- template.php
> EUTHEME-308 (Unsetting the region header bottom when there's no breadcrumb)

- css/style-sass-components.css
- js/europa.js
- sass/components/_timeline.scss
- sass/components/html/timeline.html
> EUTHEME-304 (Timeline component)

- template.php
> EUTHEME-309 (Setting tabs for taxonomy entities only in full view mode)

- sass/components/_listing.scss
> EUTHEME-315 (Highlighted Listings instead of Homepage Listings)

- templates/form_element/form_element.component.inc
> NEPT-1172: Quick fixes detected by behat tests

- css/style-sass-base.css
- css/style-sass-components.css
- sass/base/_checkbox.scss
- sass/base/html/checkbox.html
- template.php
* EUTHEME-315- Highlighted listings
* DTSSB-2111 - Link in checkboxes label
* DTTSB-2111 - Fixing typo
* DTTSB-2111: Improving patterns and logic.
* DTTSB-2111 - Supporting required checkbox
* DTTSB-2111 - Supporting required checkbox
> DTSSB-2111  (Link in checkboxes label) (#202)
